spring:
  application:
    name: erp

  # Database Configuration (MySQL)
  datasource:
    url: jdbc:mysql://localhost:30315/meow_db?useSSL=false&serverTimezone=Asia/Taipei&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useUnicode=true
    username: meow_user
    password: meow_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

  # Redis Configuration
#
#  data:
#    redis:
#      host: localhost
#      port: 30319
#      timeout: 2000ms
#      lettuce:
#        pool:
#          max-active: 8
#          max-idle: 8
#          min-idle: 0
# Server Configuration
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
  packages-to-scan: erp
  paths-to-match: /api/**

# Logging Configuration
logging:
  level:
    # org.hibernate.SQL: DEBUG
    # org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    erp.core.interceptor.RequestResponseLoggingInterceptor: INFO
    erp.core.filter.ContentCachingFilter: INFO
  # file:
  #   name: logs/application.log
  #   path: logs/
  pattern:
    # file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  # logback:
  #   rolling-policy:
  #     max-file-size: 10MB
  #     max-history: 30